# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp
# Selectively Loading
load_meta_cols: [ itemID, description, title, category ]

TEXT_ID_FIELD: description
filter_out_cod_start_users: True

inter_file_name: 'sports_and_outdoors.inter'
text_file_name: 'meta-games-indexed.csv'

vision_feature_file: 'image_feat.npy'
text_feature_z_file: 'text_feat_z.npy'
text_feature_p_file: 'text_feat_p.npy'

item_graph_dict_file: 'item_graph_dict.npy'
max_img_size: 256

field_separator: "\t"

gamma: [0.2]
tau: [ 0.8 ]

alpha_text_p: 0.5
alpha_interest: 0.3
alpha_text_z: 0.1
alpha_image: 0.1